language: go
go:
- 1.10.x
before_script:
- scripts/install_local_k8s.sh
script:
- make
- make integration-test
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make package
deploy:
  provider: releases
  api_key:
    secure: ONHaJn+2Yko9bUTd75yEf7feUBCU3Hzij6bMMj4WhmI3oRLKieRTQYh0Sikd0E2KGkVvAp4KT/me3CXIJQ4/DSLZLykfPB5HXrhGXUGg5uqM1T1R9Gamxv+bMIhXSoL4Ok5sglFgCcB40KncUrviSc+CiSAlzbeRknYxtVHkQIHM88RwXxCGuwcNXjm0PuRX0hhcU4qgB3HTMScjMpvD+Iuyj2B0FAbOjcO0nR68GszSds2z5TtA/sAKUf380KLiTp/LQx4CPxY8UBtunlsjjGILuaOTI9gRrbycE1D/u6lm49HJb3dMASTGPQUcsQGP8YgeY2fIvFKeTsQeNthDZw7UYWr3J6gB6K7bMmiKCwfGwVdEdikp19BgkvssGst5v0bG0EmB211JFv61JD1eJMjG1LmWILWFaOrzCnB6jMkjxLMIYRLjmJGLHr90GXaw/KXFOKVskc9Bih217p0vKUmPumTA0LFtUoMEwzsHBrICKkxg8LDutuLOhNvOMGGFWNoAY1H6rTngI3oBg5DxfIWaLWJD/Bxotg+kI3tOxphq5jMUNa2q/VIbTV4gmZWKj+Iyt/n9poHj2UkPhpZ/GdHbbVZi7yJdKuCeN5ikojPF4G7bmrXaSVrTDlal1iwz0M6aHSFtvfP8KYPdjQKVhsB4oRT/c9mQD6Ylzmekg9s=
  file: target/*.zip
  on:
    repo: allegro/vaas-registration-hook
