name: golangci
on:
  push:
    tags:
      - v[0-9]+.*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and test project
        run: |
          make